
let projectSynthetica = {
  'type':'project-section',
  'images':[
    'images/Synthetica/0.png',
    'images/Synthetica/1.png',
    'images/Synthetica/2.png',
    'images/Synthetica/3.png',
    'images/Synthetica/4.png',
    'images/Synthetica/5.png',
  ],
  'project-link':'https://synthetica.herokuapp.com/',
  'text-container':{
    'title':'Synthetica',
    'subtitle':'React, Node.js, JavaScript, SCSS, Heroku, ChatGPT',
    'text':[
      'A visual literarure series of poems, short stories and experimental pieces written by AI and contained by human design.',
    ],
  },
  'links':[
    {
      'css':'link white',
      'href':'https://github.com/eric6cho/synthetica',
      'external link':true,
      'icon':{
        'type':'image',
        'css':'icon image-icons',
        'src':'icons/github.png',
        'alt':'GitHub',
      },
    },
    {
      'css':'link white',
      'href':'https://synthetica.herokuapp.com/',
      'external link':true,
      'icon':{
        'type':'icon',
        'css':'icon material-icons',
        'text':'launch',
      },
    },
  ],   
};

let projectPixelMemories = {
  'type':'project-section',
  'images':[
    'images/Pixel Memories/0.png',
    'images/Pixel Memories/1.png',
    'images/Pixel Memories/2.png',
    'images/Pixel Memories/3.png',
    'images/Pixel Memories/4.png',
  ],
  'project-link':'https://pixel-memories.herokuapp.com/',
  'text-container':{
    'title':'Pixel Memories',
    'subtitle':'React, Node.js, JavaScript, SCSS, Heroku, Image Mesh',
    'text':[
      'A gallery of pixel art generated by my Image Mesh program using images from my camera roll.',
    ],
  },
  'links':[
    {
      'css':'link white',
      'href':'https://github.com/eric6cho/pixel-memories',
      'external link':true,
      'icon':{
        'type':'image',
        'css':'icon image-icons',
        'src':'icons/github.png',
        'alt':'GitHub',
      },
    },
    {
      'css':'link white',
      'href':'https://pixel-memories.herokuapp.com/',
      'external link':true,
      'icon':{
        'type':'icon',
        'css':'icon material-icons',
        'text':'launch',
      },
    },
  ],   
};

let projectImageMesh = {
  'type':'project-section',
  'images':[
    'images/Image Mesh/0.png',
    'images/Image Mesh/1.png',
    'images/Image Mesh/2.png',
    'images/Image Mesh/3.png',
    'images/Image Mesh/4.png',
    'images/Image Mesh/5.png',
    'images/Image Mesh/6.png',
    'images/Image Mesh/7.png',
  ],
  'project-link':'https://image-mesh.herokuapp.com/',
  'text-container':{
    'title':'Image Mesh',
    'subtitle':'React, Node.js, JavaScript, SCSS, Heroku',
    'text':[
      'A full stack web application that allows users to create pixel art and edited photos. Users can apply filters and generate '+
      'new photos from images sourced online. Creates a palette based on the colors in the edited photo, and allows users to '+
      'create unique pixel maps and gradients from the palette.',
      'Click the links below to view the GitHub repository of the client project and the deployed application.',
    ],
  },
  'links':[
    {
      'css':'link white',
      'href':'https://github.com/eric6cho/image-mesh-react',
      'external link':true,
      'icon':{
        'type':'image',
        'css':'icon image-icons',
        'src':'icons/github.png',
        'alt':'GitHub',
      },
    },
    {
      'css':'link white',
      'href':'https://image-mesh.herokuapp.com/',
      'external link':true,
      'icon':{
        'type':'icon',
        'css':'icon material-icons',
        'text':'launch',
      },
    },
  ],   
};

let projectPixelfy =    
{
  'type':'project-section',
  'images':[
    'images/Spotify Pixelfy/0.png',
  ],
  'project-link':'https://spotify-pixelfy.herokuapp.com/',
  'text-container':{
    'title':'Pixelfy',
    'subtitle':'React, Node.js, JavaScript, SCSS, Heroku',
    'text':[
      'An ongoing full stack project made to generate a pixel art collection of the top artists of a Spotify listener. '+
      'Uses the Spotify API and my own Image Mesh API to retrieve artist images and create pixel art versions. ',
      'Click the links below to view the GitHub and the deployed application.',
    ],
  },
  'links':[
    {
      'css':'link white',
      'href':'https://github.com/eric6cho/spotify-pixelfy',
      'external link':true,
      'icon':{
        'type':'image',
        'css':'icon image-icons',
        'src':'icons/github.png',
        'alt':'GitHub',
      },
    },
    {
      'css':'link white',
      'href':'https://spotify-pixelfy.herokuapp.com/',
      'external link':true,
      'icon':{
        'type':'icon',
        'css':'icon material-icons',
        'text':'launch',
      },
    },
  ],   
};

let projectRemodel = {
  'type':'project-section',
  'images':[
    'images/Remodel Storefront/0.png',
    'images/Remodel Storefront/1.png',
    'images/Remodel Storefront/2.png',
    'images/Remodel Storefront/3.png',
    'images/Remodel Storefront/4.png',
    'images/Remodel Storefront/5.png',
    'images/Remodel Storefront/6.png',
    'images/Remodel Storefront/7.png',
    'images/Remodel Storefront/8.png',
    'images/Remodel Storefront/9.png',
  ],
  'project-link':'https://remodel-storefront.herokuapp.com/',
  'text-container':{
    'title':'Remodel Storefront',
    'subtitle':'React, Node.js, JavaScript, SCSS, Heroku',
    'text':[
      'A project made to replicate the components and functionalities seen in a '+
      'ecommerce website with many design languages for single template components. '+
      'Inspired by working with clients with requirements to implement many '+
      'different components with similar structures. Built over 30 unique design '+
      'combinations and visual themes that can be applied to each component template.',
      'Click the links below to view the GitHub and the deployed application.',
    ],
  },
  'links':[
    {
      'css':'link white',
      'href':'https://github.com/eric6cho/Remodel-Storefront',
      'external link':true,
      'icon':{
        'type':'image',
        'css':'icon image-icons',
        'src':'icons/github.png',
        'alt':'GitHub',
      },
    },
    {
      'css':'link white',
      'href':'https://remodel-storefront.herokuapp.com/',
      'external link':true,
      'icon':{
        'type':'icon',
        'css':'icon material-icons',
        'text':'launch',
      },
    },
  ],   
};

let projectCryptoCharts =  {
  'type':'project-section',
  'images':[
    'images/Crypto Price Charts/0.png',
    'images/Crypto Price Charts/1.png',
    'images/Crypto Price Charts/2.png',
    'images/Crypto Price Charts/3.png',
    'images/Crypto Price Charts/4.png',
    'images/Crypto Price Charts/5.png',
  ],
  'project-link':'https://github.com/eric6cho/Crypto-Price-Chart',
  'text-container':{
    'title':'Cryptocurrency Price Charts',
    'subtitle':'React, Node.js, JavaScript, SCSS, Heroku',
    'text':[
      'A personal use, full stack data visualization project that gathers data of '+
      'cryptocurrency assets and the market as a whole. Displays live and historical '+
      'prices and compiled technical indicators of over 200 cryptocurrency assets, '+
      'while using the TradingView API to create interactive charts for this data. ',
      'Click the links below to view the GitHub and the deployed application.',
    ],
  },
  'links':[
    {
      'css':'link white',
      'href':'https://github.com/eric6cho/Crypto-Price-Chart',
      'external link':true,
      'icon':{
        'type':'image',
        'css':'icon image-icons',
        'src':'icons/github.png',
        'alt':'GitHub',
      },
    },
  ],
};

let projectWand = {
  'type':'project-section',
  'images':[
    'images/WAND/0.jpg',
    'images/WAND/1.jpg',
  ],
  'project-link':'https://devpost.com/software/wand-hbf0ke',
  'text-container':{
    'title':'WAND: Walking Aid Notification Device',
    'subtitle':'Python (OpenCV, gTTS)',
    'text':[
      'A project made to assist people with blindness by using sensors and image '+
      'analysis. Compiled numerical data from an ultrasound sensor, analyzed images '+
      'with object detection, and used text to speech technology to output '+
      'information in an accessible way. Completed a working handheld prototype in '+
      'a team of four at the 2020 UGA Hackathon and won second place.',
      'Click the link below to read more about the project.',
    ],
  },
  'links':[
    {
      'css':'link white',
      'href':'https://devpost.com/software/wand-hbf0ke',
      'external link':true,
      'icon':{
        'type':'icon',
        'css':'icon material-icons',
        'text':'launch',
      },
    },
  ],
};


export let navData = {
  'primary':{
    'links':[
      {
        'css':'link nav-title',
        'href':'#Home',
        'text':'Eric Cho',
        'external link':false,
      },
      {
        'css':'link nav-primary',
        'href':'#Home',
        'text':'Home',
        'external link':false,
        'icon':{
          'type':'icon',
          'css':'icon material-icons',
          'text':'home',
        },
      },
      {
        'css':'link nav-primary',
        'href':'#About',
        'text':'About',
        'external link':false,
        'icon':{
          'type':'icon',
          'css':'icon material-icons',
          'text':'person',
        },
      },
      {
        'css':'link nav-primary',
        'href':'#Education',
        'text':'Education',
        'external link':false,
        'icon':{
          'type':'icon',
          'css':'icon material-icons',
          'text':'school',
        },
      },
      {
        'css':'link nav-primary',
        'href':'#Experience',
        'text':'Experience',
        'external link':false,
        'icon':{
          'type':'icon',
          'css':'icon material-icons',
          'text':'work',
        },
      },
      {
        'css':'link nav-primary',
        'href':'#Projects',
        'text':'Projects',
        'external link':false,
        'icon':{
          'type':'icon',
          'css':'icon material-icons',
          'text':'code',
        },
      },
      {
        'css':'link nav-primary',
        'href':'#About',
        'text':'Resume',
        'external link':false,
        'icon':{
          'type':'icon',
          'css':'icon material-icons',
          'text':'article',
        },
      },
    ],
  },
  'secondary':{
    'links':[
      {
        'css':'link nav-secondary',
        'href':'mailto:eric6cho@gmail.com',
        'text':'eric6cho@gmail.com',
        'external link':true,
      },
      {
        'css':'link nav-secondary',
        'href':'https://www.linkedin.com/in/6cho/',
        'external link':true,
        'icon':{
          'type':'image',
          'css':'icon image-icons',
          'src':'icons/linkedin.png',
          'alt':'LinkedIn',
        },
      },
      {
        'css':'link nav-secondary',
        'href':'https://github.com/eric6cho',
        'external link':true,
        'icon':{
          'type':'image',
          'css':'icon image-icons',
          'src':'icons/github.png',
          'alt':'GitHub',
        },
      },
    ],
  },
};

export let pageData = {
  'sections':{
    'home':{
      'id':'Home',
      'title':'Eric Cho',
      'description':[
        'Full Stack Developer',
        'University of Georgia, 2020',
        'Based in Atlanta, GA',
      ],
    },
    'contents':{ 
      
      'id':'Contents',
      'header':{
        'icon':'menu_book',
        'title':'Contents',
      },
      'subsections':[
        {
          'type':'contents-section',
          'data':{ 
            'About':['Introduction','Contact Links'],
            'Education':['University of Georgia','National University of Singapore'],
            'Experience':['Perficient','University of Georgia'],
            'Projects':['Synthetica','Pixel Memories','Image Mesh','Pixelfy','Remodel Storefront','Crypto Price Charts','WAND'],
          },
        
        },
      ],
      
      
     

    },
    'about':{
      'id':'About',
      'header':{
        'icon':'person',
        'title':'About',
      },
      'subsections':[
        {
          'type':'about-section',
          'text-container':[
            'my name is Eric Cho and I am an alumni of The University of Georgia with a bachelors in Computer Science. My earliest interaction with any code '+
            'was in middle school where my friends and I found out how to click "inspect element" and mess around with each other\'s website pages. ',
            'I thought it '+
            'was just a funny gag to pull, but little did I know, that would set me on a path where I would get the chance to start coding in 2016 during my '+
            'freshman year of college and continue to learn, not only in the United States, but abroad in Singapore as well. ',
            'After graduating, finding a niche in '+
            'the world of tech was pretty straightforward. I grew up in a family of artists, so becoming a developer that focuses on full stack and frontend felt '+
            'like the most natural way to be involved in both tech and visual design.', 
            'As of now, I have had the chance to be a part of amazing teams to create online products and solutions used by businesses across the country, and it '+
            'has helped solidify my focus on creating online experiences to be able to reach and impact more people.',
            'It continues to be my goal today.',  
          ],
          'link-container':{
            'header':'Some Links:',
            'subheader':'I have some links posted below; feel free to check them out.',
            'links':[
              {
                'css':'link button white contact-link',
                'href':'https://www.linkedin.com/in/6cho/',
                'text':'LinkedIn',
                'external link':true,
                'icon':{
                  'type':'image',
                  'css':'icon image-icons',
                  'src':'icons/linkedin.png',
                  'alt':'LinkedIn',
                },
              },
              {
                'css':'link button white contact-link',
                'href':'https://github.com/eric6cho',
                'text':'GitHub',
                'external link':true,
                'icon':{
                  'type':'image',
                  'css':'icon image-icons',
                  'src':'icons/github.png',
                  'alt':'GitHub',
                },
              },
              {
                'css':'link button white contact-link',
                'href':'resume/Eric Cho Resume.pdf',
                'text':'Resume',
                'external link':true,
                'icon':{
                  'type':'icon',
                  'css':'icon material-icons',
                  'text':'article',
                },
              },
            ],
          },
        },
      ],
    },
    'education':{
      'id':'Education',
      'header':{
        'icon':'school',
        'title':'Education',
      },
      'subsections':[
        {
          'type':'education-section',
          'title':'University of Georgia',
          'subtitle':['Undergraduate Studies','Aug 2016 - Jul 2020'],
          'rows':[
            {
              'title':'Degree',
              'entry':'Bachelor of Science in Computer Science',
            },
            {
              'title':'Emphasis',
              'entry':'Internet Information Technology',
            },
            {
              'title':'Certificate',
              'entry':'Applied Data Science',
            },
            {
              'title':'GPA',
              'entry':'3.40/4.00',
            },
            {
              'title':'Coursework',
              'entry':
                'Computer Networks, Data Mining, Data Science, Data Structures, Discrete Mathematics, '+
                'Linear Algebra, Numerical Simulations, Software Development, Systems Programming, '+
                'Theory of Computation, Web Programming',
            },
            {
              'title':'Events',
              'entry':
                'National University of Singapore Exchange Program (2019), '+
                '2nd place winner at UGAHacks5 (2020)',
            },
            {
              'title':'Organizations',
              'entry':
                'Asian American Student Association, Association for Computing Machinery, Vietnamese '+
                'Student Association, Office of Global Engagement',
            },
            {
              'title':'Scholarships',
              'entry':'Hope Scholarship, McMullan Study Abroad Scholarship',
            },
          ],
        },
        {
          'type':'education-section',
          'title':'National University of Singapore',
          'subtitle':['Exchange Program','Jan 2019 - May 2019'],
          'rows':[
            {
              'title':'Program',
              'entry':'School of Computing, Student Exchange Programme',
            },
            {
              'title':'Coursework',
              'entry':'Computer Architecture, Database Systems',
            },
          ],
        }

      ],
    },
    'experience':{
      'id':'Experience',
      'header':{
        'icon':'work',
        'title':'Experience',
      },
      'subsections':[
        {
          'type':'experience-section',   
          'title':'Associate Technical Consultant',
          'location':'Perficient',
          'subtitle':'May 2020 - Dec 2021',
          'responsibilities':[
            'Took on a frontend and full stack developer role on a variety of internal and client '+
            'facing projects.',
            'Used JavaScript, React, C#, SCSS and Sitecore to build components, services, interfaces, and stylesheets. ',
            'Provided support to site content authors and other frontend developers.',
            'Regularly participated in client facing demos.',
          ],
          'client-projects':{
            'title':'More detailed descriptions of these project engagements are listed below:',
            'projects':[
              {
                'id':'project-1',
                'css':'active',
                'title':'Healthcare Provider Client',
                'subtitle':'Lead Frontend Developer',
                'responsibilities':[
                  'Took a role as the lead frontend developer for a site that saw a successful launch.',
                  'Implemented the UI and frontend logic of the main "Find a Doctor/Location" functionality of '+
                  'the project and various components throughout the site.',
                  'Regularly participated in client facing demos.',
                  'Provided support to other frontend developers.',
                ],
              },
              {
                'id':'project-2',
                'title':'Home Renovation Client ',
                'subtitle':'Frontend Developer',
                'responsibilities':[
                  'Performed major frontend bugs fixes that were critical to the project\'s completion.',
                  'Worked on various components throughout the site, including the main "Find a Dealer" '+
                  'functionality of the site.',
                  'Regularly participated in client facing demos and acted as a contact point for the development team on the client\'s end.',            
                ],
              },
              {
                'id':'project-3',
                'title':'Healthcare Provider Client',
                'subtitle':'Frontend Developer',
                'responsibilities':[
                  'Built and fixed the UI and frontend logic of components found throughout the site.',
                  'Built content pages for patient devices and articles, and tested all components on '+
                  'those pages.',
                  'Provided support to site content authors and other frontend developers.',
                ],
              },
              {
                'id':'project-4',
                'title':'Internal Project',
                'subtitle':'Full Stack Developer',
                'responsibilities':[
                  'Built full stack features for an internal site used to guide the training '+
                  'process of new interns.',
                  'Built the front and backend of the projects page, which allowed users to create and '+
                  'participate in company/office initatives.',
                  'Built UI for course content pages, projects page, and admin pages. Provided maintenence '+
                  'to the UI for all parts of the site.',
                ],
              },
            ],
          },
        },
        {
          'type':'experience-section',   
          'title':'Calculus Tutor',
          'location':'University of Georgia',
          'subtitle':'Sep 2017 - May 2018',
          'responsibilities':[
            'Taught key mathematical concepts and their practical uses during daily walk-in '+
            'tutoring sessions of up to 20 students. ',
            'Coordinated with other graduate tutors to help students prepare for exams in '+
            'Precalculus and Calculus I - III.',
            'Students experienced noticeable improvements and came back regularly to study.',
          ],
        },
      ],
    },
    'projects':{
      'id':'Projects',
      'header':{
        'icon':'code',
        'title':'Projects',
      },
      'subsections':[
        projectSynthetica,
        projectPixelMemories,
        projectImageMesh,
        projectPixelfy,
        projectRemodel,
        projectCryptoCharts,
        projectWand,
      ],
    },
  },
};

